### PR TITLE
move `create_user` logic to utils

### PR DESCRIPTION
**Pull request by spumer**
Here is new improvement ;)

So, in some cases i got user details from another place (not from oauth) and whant to save it in database, but i want allow users auth with same credentials later (email, username).

### CODE REVIEW

**Comment by spumer** [comment]
So, can you explain why RemoteUser model exists?
What is use-case?

**Comment by richardmansfield** [comment]
It lets the client site work out which of its local users is logging in,
based on the username provided by the auth server. Useful when you can't
rely on usernames being the same on client & server, because maybe you have
some previously existing non-oauth users on the client, and when you can't
rely on email addresses being unique or even existing.

**Comment by spumer** [comment]
Which minimal django version you really support?

I saw some logic to generate username if it already exists. It's looks complicated and i have some problems with that when try to refactoring tests.
But it's fixed and all LTS releases have it:

https://github.com/django/django/pull/5891
https://code.djangoproject.com/ticket/20846

**Comment by richardmansfield** [comment]
I only use it on Django 1.11+ now

**Pull request merged**
